name: Pptx to Image
on:
  # push:
  pull_request:
    paths:
      - 'quiz/quiz.pptx'
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  
  build:

    if: github.actor == 'ogawa3427' || github.actor == 'MAPLE0212'

    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    defaults:
      run:
        working-directory: ./quiz
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update ImageMagick policy
        run: |
          sudo sed -i 's/<policy domain="coder" rights="none" pattern="PDF"/<policy domain="coder" rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y tree
          tree -L 2
          sudo apt install -y libreoffice
          sudo apt install poppler-utils
          sudo apt install -y fonts-hanazono fonts-ipafont-gothic fonts-ipafont-mincho
          # 必要なフォントをインストール
          sudo apt install -y fonts-hanazono fonts-ipafont-gothic fonts-ipafont-mincho

      - name: Check if PPTX file exists
        run: |
          if [ ! -f "quiz.pptx" ]; then
            echo "PPTX file does not exist"
          fi

      - name: Convert PPTX to Image
        run: |
          ls -la
          libreoffice --headless --convert-to pdf quiz.pptx --outdir .
          ls -la
          if [ ! -f "quiz.pdf" ]; then
            echo "PDF conversion failed"
            exit 1
          fi
          pdftoppm -png quiz.pdf quiz

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Convert PPTX to Image"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
