name: Pptx to Image
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./quiz
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libreoffice
          sudo apt install -y imagemagick

      - name: Check if PPTX file exists
        run: |
          if [ ! -f "quiz.pptx" ]; then
            echo "PPTX file does not exist"
            exit 1
          fi

      - name: Convert PPTX to Image
        run: |
          libreoffice --headless --convert-to pdf quiz.pptx --outdir quiz
          if [ ! -f "quiz.pdf" ]; then
            echo "PDF conversion failed"
            exit 1
          fi
          convert -density 300 quiz.pdf -quality 90 quiz-%d.png

      # - name: Upload Image
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: quiz
      #     path: quiz-*.png

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Convert PPTX to Image"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}